version: '3'
volumes:
  database-data:
    driver: local
services:
  database:
    image: postgres # use latest official postgres version
    env_file:
      - database.env # configure postgres environment
    volumes:
      - database-data:/var/lib/postgresql/data/ # persist data even if container shuts down
    ports:
      - 5432:5432